CREATE TABLE ALUNOS (ID INT,  RA INT, NOME VARCHAR(512));

DELIMITER //

CREATE PROCEDURE POPULA_ALUNOS()
BEGIN
	DECLARE I INTEGER;
	DECLARE NOME VARCHAR(512);
	SET I=1;
	WHILE (I < 10000) DO
		SET NOME = CONCAT("ALUNO", I);
		INSERT INTO ALUNOS VALUES(I, RAND(), NOME);
		SET I=I+1;
	END WHILE;

END//
DELIMITER;
