USE unasp;
CREATE TABLE MENSALIDADES (CODCURSO INT, VALOR FLOAT);
INSERT INTO MENSALIDADES VALUES(1, 350);
INSERT INTO MENSALIDADES VALUES(2, 400);
INSERT INTO MENSALIDADES VALUES(3, 500);

DROP PROCEDURE VALOR;

DROP PROCEDURE VALOR;

DELIMITER //

CREATE PROCEDURE VALOR(IN CURSO INT, IN VENCIMENTO DATE)
BEGIN 
DECLARE PRECO FLOAT;
SET PRECO = (SELECT MENSALIDADES.VALOR FROM MENSALIDADES WHERE MENSALIDADES.CODCURSO = CURSO);
IF VENCIMENTO  <= NOW() THEN	
	SELECT PRECO*0.9;
ELSE
	SELECT PRECO*1.1;
END IF;
    
END //

CALL VALOR(1, '2015-30-08');
CALL VALOR(1, '2015-10-08');
